name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: docker build -t my-docker-app .
        
      - name: Test Docker Image
        run: |
          docker run -d -p 8080:80 --name test-container my-docker-app
          sleep 5
          curl --fail http://localhost:8080 || (echo "Test failed" && exit 1)
          docker stop test-container
          
      - name: Tag for Docker Hub
        run: docker tag my-docker-app khawlagr12/my-docker-app:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u khawlagr12 --password-stdin
          
      - name: Push to Docker Hub
        run: docker push khawlagr12/my-docker-app:latest